import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter();

  const handlePlaceOrder = () => {
    alert('order placed successfully');
    // navigate user to produc list page
    router.push('/product');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.JS Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        Home Page
      </h1>
      <Link href='/blog'>
        Blog
      </Link> <br/>
      <Link href='/product'>
        Product
      </Link> <br/>
      <button
        onClick={handlePlaceOrder}
      >
        Place Order
      </button>
    </div>
  )
}
